import consola from "consola";
import fs from "fs";
import path from "path";
import readline from "readline";

import { GenerateItemsEnum } from "./lib/GenerateItemsEnum.ts";

const itemsJsonPath = path.join(process.cwd(), "items.json");

async function main() {
  try {
    // @note time start
    const startTime = Date.now();

    const generator = new GenerateItemsEnum();
    generator.loadFromFile(itemsJsonPath);

    const itemsVersion = generator.itemsVersion;
    const itemsCount = generator.itemsCount;
    consola.info(`Loaded items.json - Version: ${itemsVersion}, Items Count: ${itemsCount}`);

    // prompt for optional prefix to prefix enum names (press Enter to skip)
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const ask = (q: string) => new Promise<string>((res) => rl.question(q, (answer) => res(answer)));
    const prefix = (await ask("Enter optional prefix (press Enter to skip): ")).trim();
    rl.close();

    if (prefix) consola.info(`Using prefix: '${prefix}'`);

    const enumString = generator.buildEnum(4, prefix);

    const creditComment = `/**
 * @brief Generated by Growtopia Items Enum Generator
 *
 * Version: ${itemsVersion}, Items Count: ${itemsCount}
 * Generated on: ${new Date().toISOString()}
 *
 * @see https://github.com/GTPSHAX/growtopia-items-enum-generator - our repository
 */
`;

    const result = `#ifndef ITEMS_ENUM_H
#define ITEMS_ENUM_H

${creditComment}${enumString}
#endif // ITEMS_ENUM_H
`;

    fs.writeFileSync(path.join(process.cwd(), "ItemsEnum.h"), result, "utf-8");
    consola.success("Enum generated successfully:\n");

    // @note time end
    const endTime = Date.now();
    consola.info(`Time taken: ${(endTime - startTime) / 1000} seconds`);
  } catch (error) {
    consola.error("An error occurred:", error);
    process.exit(1);
  }
}

main();
